name: start_trek
description: "Start Trek - 儿童英语学习应用"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  audioplayers: ^6.0.0
  http: ^1.2.1
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  lottie: ^3.1.2
  cached_network_image: ^3.3.1
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0
  flutter_tts: ^4.0.2
  path_provider: ^2.1.3
  fl_chart: ^0.68.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  integration_test:
    sdk: flutter
  
  # JSON序列化代码生成
  json_serializable: ^6.7.1
  
  # Freezed代码生成
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  
  # 资源文件配置
  assets:
    - assets/images/
    - assets/audio/
    - assets/animations/
    - assets/data/
  
  # 字体配置
  # fonts:
  #   - family: KidsFont
  #     fonts:
  #       - asset: assets/fonts/KidsFont-Regular.ttf
  #       - asset: assets/fonts/KidsFont-Bold.ttf
  #         weight: 700
